### ISSUE TITLE
Mockup of Database

### ISSUE THREAD

**Issue by aOverholt** [Macks1776/RSI-Calendar#5]
- [x] Event
- [x] Attachment
- [x] Employee

**Comment by Macks1776** [comment]
There is seed data for each table so I assume that's what you meant

**Comment by aOverholt** [comment]
I was actually talking about getting an easy to understand visual representation of how our database works in case we have to share it in class tomorrow. I actually did it and put it in discord in the meeting notes for tomorrow. 

Seed data is something that I hadn't thought about yet, but will definitely be needed! Thats great that you already did it

**Comment by aOverholt** [comment]
Image in Discord "Meeting_9-7_730"
